import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LoginHeader } from "@/libs/components/LoginHeader";
import { VStack } from "../../styled-system/jsx/vstack";
import { Box } from "../../styled-system/jsx/box";
import { Footer } from "@/libs/components/Footer"
import { Providers } from "@/libs/utility/providers/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
})  {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Box
        width={'screen'}
        overflowX={'hidden'}
        minHeight={'screen'}>
          {children}
          <Footer/>
        </Box>
      </body>
    </html>
  );
}
